/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import database.H2Prepare;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;

/**
 *
 * @author amit
 */
public class FolderScan3 extends javax.swing.JPanel implements Runnable {

    private final String dirPath;
    private final ArrayList<String> fileTypes;
    private final String words;
    private final ArrayList<Long> fileHashList;
    private int totalFiles = 0, relatedFiles = 0;
    private HashMap<String, Integer> relatedFilesCount = new HashMap<>();
    private int progressBarMin = 0, progressBarMax = 100, progressBarVal = 0;
    private boolean threadOK = true;
    private final boolean DEBUG = true;

    /**
     * Creates new form StatusBar
     *
     * @param dirPath
     * @param fileTypes
     * @param words
     */
    public FolderScan3(String dirPath, ArrayList<String> fileTypes, String words) {
        this.dirPath = dirPath;
        this.fileTypes = fileTypes;
        this.words = words;
        this.fileHashList = H2Prepare.getFileHashList();
        fileTypes.forEach((String _item) -> {
            relatedFilesCount.put(_item, 0);
        });
        initComponents();
        progressBarMin = jProgressBar1.getMinimum();
        progressBarMax = jProgressBar1.getMaximum();
        jProgressBar1.setString(dirPath);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jButton1 = new javax.swing.JButton();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setMaximumSize(null);

        jProgressBar1.setString("");
        jProgressBar1.setStringPainted(true);

        jButton1.setText("Stop");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButton1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Thread.sleep(100);
            threadOK = false;
        } catch (InterruptedException ex) {
            System.err.println(ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        if (DEBUG) {
            System.out.println("Scanning started for " + dirPath);
        }
        scanDirRecursive(new File(dirPath));
        if (DEBUG) {
            System.out.println("Scanning finished for " + dirPath + "[Total:" + totalFiles + ", Related:" + relatedFiles + ", " + relatedFilesCount + "]");
        }
        setVisible(false);
        getParent().remove(this);
        if (!words.isEmpty()) {
            new FileNameSearch(dirPath.hashCode(), fileTypes, words).start();
            if (MainLayout02.contentSearchChk.isSelected()) {
                new ContentSearch(dirPath.hashCode(), fileTypes, words).start();
            }
        }
    }

    String file_name;
    String file_type;
    String file_path;
    long fileHash;
    File[] files;

    private void scanDirRecursive(File dir) {
        try {
            files = dir.listFiles();
            if (files != null) {
                for (File file : files) {
                    if (threadOK) {
                        if (file.isDirectory()) {
                            scanDirRecursive(file);
                        } else {
                            totalFiles++;
                            file_name = file.getName().toLowerCase();
                            file_type = file_name.substring(file_name.lastIndexOf('.') + 1);
                            if (fileTypes.contains(file_type)) {
                                file_name = file_name.substring(0, file_name.lastIndexOf('.'));
                                file_path = file.getCanonicalPath();
                                fileHash = file_path.hashCode();
                                if (!fileHashList.contains(fileHash) && H2Prepare.insertRecords(file_name, file_path, file_type, file.length(), file.lastModified(), fileHash, 0, dirPath.hashCode()) == 1) {
                                    relatedFiles++;
                                    relatedFilesCount.put(file_type, relatedFilesCount.get(file_type) + 1);
                                }
                                jProgressBar1.setValue(progressBarVal++);
                                if (progressBarVal >= progressBarMax) {
                                    progressBarVal = progressBarMin;
                                }
                            }
                        }
                    }
                }
            }
        } catch (IOException e) {
            System.err.println(e.getMessage());
        }
    }
}
