/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import database.H2Prepare;
import java.awt.HeadlessException;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author amit
 */
public class FolderScan3 extends javax.swing.JPanel implements Runnable {

    private final String path, searchString, action;
    private String file_name, file_type, file_path;
    private ArrayList<String> fileTypes;
    private ArrayList<Long> fileHashList;
    private int totalFiles = 0, relatedFiles = 0, progressBarMin = 0, progressBarMax = 100, progressBarVal = 0;
    private HashMap<String, Integer> relatedFilesCount = new HashMap<>();
    private boolean threadOK = true;
    private final boolean DEBUG = true;
    private long fileHash;
    private File[] files;

    /**
     * Creates new form StatusBar
     *
     * @param path
     * @param fileTypes
     * @param searchString
     * @param action
     */
    public FolderScan3(String path, ArrayList<String> fileTypes, String searchString, String action) {
        this.path = path;
        this.fileTypes = fileTypes;
        this.searchString = searchString;
        this.fileHashList = H2Prepare.getFileHashList();
        this.action = action;
        fileTypes.forEach((String _item) -> {
            relatedFilesCount.put(_item, 0);
        });
        initComponents();
        progressBarMin = jProgressBar1.getMinimum();
        progressBarMax = jProgressBar1.getMaximum();
        jProgressBar1.setString(path);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jButton1 = new javax.swing.JButton();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setMaximumSize(null);

        jProgressBar1.setString("");
        jProgressBar1.setStringPainted(true);

        jButton1.setText("Stop");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButton1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Thread.sleep(100);
            threadOK = false;
        } catch (InterruptedException ex) {
            System.err.println(ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        try {
            File file = new File(path);
            if (file.isDirectory()) {
                if (DEBUG) {
                    System.out.println("Scanning started for " + path + " and type " + fileTypes + "[" + Thread.currentThread().getId() + "]");
                }
                scanDirRecursive(file);
                if (DEBUG) {
                    System.out.println("Scanning finished for " + path + "[Total:" + totalFiles + ", Related:" + relatedFiles + ", " + relatedFilesCount + "]");
                }
                jProgressBar1.setValue(progressBarMax);
                if ("SCAN".equals(action)) {
                    showStatus(relatedFiles + " new files found.", path);
                }

                if ("SEARCH".equals(action)) {
                    if (MainLayout02.nameSearchChk.isSelected()) {
                        new FileNameSearch(path, fileTypes, searchString).start();
                    }
                    if (MainLayout02.contentSearchChk.isSelected()) {
                        new ContentParse(path.hashCode(), fileTypes, searchString).start();
                    }
                    //|| MainLayout02.tagSearchChk.isSelected()
                }
            } else if (file.isFile()) {
                file_name = file.getName().toLowerCase();
                file_type = file_name.substring(file_name.lastIndexOf('.') + 1);
                if (fileTypes.contains(file_type)) {
                    try {
                        file_name = file_name.substring(0, file_name.lastIndexOf('.'));
                        file_path = file.getCanonicalPath();
                        fileHash = file_path.hashCode();
                        System.out.println(file.getParent());
                        if (!fileHashList.contains(fileHash) && H2Prepare.insertRecords(file_name, file_path, file_type, file.length(), file.lastModified(), fileHash, "unknown", file.getParent().hashCode()) == 1) {
                            relatedFiles++;
                            relatedFilesCount.put(file_type, relatedFilesCount.get(file_type) + 1);
                        }
                        jProgressBar1.setValue(progressBarVal++);
                        if (progressBarVal >= progressBarMax) {
                            progressBarVal = progressBarMin;
                        }
                    } catch (IOException ex) {
                        Logger.getLogger(FolderScan3.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this.getRootPane(), "Invalid Path!", "Error", JOptionPane.ERROR_MESSAGE);
            }
            setVisible(false);
            getParent().remove(this);
        } catch (HeadlessException e) {
            System.err.println(e.getMessage());
        }
    }

    private void showStatus(String msg, String title) {
        FolderScanStatus fss = new FolderScanStatus(msg, title);
        MainLayout02.jDesktopPane1.add(fss);
        fss.setVisible(true);
    }

    private void scanDirRecursive(File dir) {
        try {
            files = dir.listFiles();
            if (files != null) {
                for (File file : files) {
                    if (threadOK) {
                        if (file.isDirectory()) {
                            scanDirRecursive(file);
                        } else {
                            totalFiles++;
                            file_name = file.getName().toLowerCase();
                            file_type = file_name.substring(file_name.lastIndexOf('.') + 1);
                            if (fileTypes.contains(file_type)) {
                                file_name = file_name.substring(0, file_name.lastIndexOf('.'));
                                file_path = file.getCanonicalPath();
                                fileHash = file_path.hashCode();
                                if (!fileHashList.contains(fileHash) && H2Prepare.insertRecords(file_name, file_path, file_type, file.length(), file.lastModified(), fileHash, "unknown", path.hashCode()) == 1) {
                                    relatedFiles++;
                                    relatedFilesCount.put(file_type, relatedFilesCount.get(file_type) + 1);
                                }
                                jProgressBar1.setValue(progressBarVal++);
                                if (progressBarVal >= progressBarMax) {
                                    progressBarVal = progressBarMin;
                                }
                            }
                        }
                    }
                }
            }
        } catch (IOException e) {
            System.err.println(e.getMessage());
        }
    }
}
