/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import database.H2Prepare;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;

/**
 *
 * @author amit
 */
public class FolderScan extends javax.swing.JPanel implements Runnable {

    private final ArrayList<String> fileTypes;
    private final ArrayList<Long> fileHashList;
    private final String dirPath;
    public int totalFiles = 0, relatedFiles = 0;
    public HashMap<String, Integer> relatedFilesCount = new HashMap<>();
    private int progressBarMin = 0, progressBarMax = 100, progressBarVal = 0;

    /**
     * Creates new form StatusBar
     *
     * @param dirPath
     * @param fileTypes
     */
    public FolderScan(String dirPath, ArrayList<String> fileTypes) {
        this.dirPath = dirPath;
        this.fileTypes = fileTypes;
        fileTypes.forEach((String _item) -> {
            relatedFilesCount.put(_item, 0);
        });
        initComponents();
        progressBarMin = jProgressBar1.getMinimum();
        progressBarMax = jProgressBar1.getMaximum();
        fileHashList = H2Prepare.getFileHashList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jButton1 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("C:\\Users\\amit\\Downloads"));
        setMaximumSize(null);
        setMinimumSize(null);

        jProgressBar1.setString("");
        jProgressBar1.setStringPainted(true);

        jButton1.setText("Stop");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButton1)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        scanDirRecursive(new File(dirPath));
        this.setVisible(false);
        getParent().remove(this);
    }

    private void scanDirRecursive(File dir) {
        File[] files = dir.listFiles();
        for (File file : files) {
            if (file.isDirectory()) {
                try {
                    jProgressBar1.setString(file.getCanonicalPath());
                } catch (IOException ex) {
                    System.err.println(ex.getMessage());
                }
                scanDirRecursive(file);
            } else {
                totalFiles++;
                try {
                    String file_name = file.getName();
                    String file_type = file_name.substring(file_name.lastIndexOf('.') + 1).toLowerCase();
                    if (fileTypes.contains(file_type)) {
                        file_name = file_name.substring(0, file_name.lastIndexOf('.'));
                        String file_path = file.getCanonicalPath();
                        long fileHash = file_path.hashCode();
                        if (!fileHashList.contains(fileHash) && H2Prepare.insertRecords(file_name, file_path, file_type, file.length(), file.lastModified(), fileHash, 0) == 1) {
                            relatedFiles++;
                            relatedFilesCount.put(file_type, relatedFilesCount.get(file_type) + 1);
                        }
                        jProgressBar1.setValue(progressBarVal++);
                        if (progressBarVal >= progressBarMax) {
                            progressBarVal = progressBarMin;
                        }
                    }
                } catch (IOException ex) {
                    System.err.println(ex.getMessage());
                }
            }
        }
    }
}
